$:
  vscode:
    - docker:
        image:
          name: docker.cnb.cool/cnbku/base/base_cnb:v2.2
      runner:
        cpus: 8
        tags: cnb:arch:amd64
      env:
        CNB_WELCOME_EXECUTE_COMMAND: bash /workspace/assets/welcome.sh
      services:
        - vscode
        - docker